# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.4.0
_src_path: https://github.com/jupyterlab/extension-template
author_email: konrad.jelen@gmail.com
author_name: Stellars Henson
has_binder: false
has_settings: false
kind: frontend
labextension_name: jupyterlab_unzip
project_short_description: Unzip files in navigator
python_name: jupyterlab_unzip_extension
repository: ''
test: true

